export const ERROR_CODES = {
  AUTH: {
    THERE_IS_A_USER_ALREADY_WITH_EMAIL: "THERE_IS_A_USER_ALREADY_WITH_EMAIL",
    INVALID_USER: "INVALID_USER",
    GOOGLE_LOGIN_FAILED: "GOOGLE_LOGIN_FAILED",
    TECHNICAL_ERR: 'TECHNICAL_ERR',
    USERNAME_PASSWORD_INCORRECT: "USERNAME_PASSWORD_INCORRECT",
    TOKEN_EXPIRED : "TOKEN_EXPIRED",
    AUTH_GOOGLE_SUCCESS: "AUTH_GOOGLE_SUC",
  },
  GEN:{
    TECHNICAL_ERR: 'TECHNICAL_ERR',
  }
};