export const API_CODES = {
  AUTH: {
    THERE_IS_A_USER_ALREADY_WITH_EMAIL: "THERE_IS_A_USER_ALREADY_WITH_EMAIL",
    INVALID_USER: "INVALID_USER",
    GOOGLE_LOGIN_FAILED: "GOOGLE_LOGIN_FAILED",
    TECHNICAL_ERR: 'TECHNICAL_ERR',
    USERNAME_PASSWORD_INCORRECT: "USERNAME_PASSWORD_INCORRECT",
    TOKEN_EXPIRED : "TOKEN_EXPIRED",
    NO_REFRESH_TOKEN : "NO_REFRESH_TOKEN",
    INVALID_REFRESH_TOKEN : "INVALID_REFRESH_TOKEN",
    AUTH_HEADER_MISSING : "AUTH_HEADER_MISSING",
    INVALID_AUTH_HEADER : "INVALID_AUTH_HEADER",
    USER_NOT_FOUND : "USER_NOT_FOUND",
    AUTH_REFRESH_TOKEN_SUC: "AUTH_REFRESH_TOKEN_SUC",
    AUTH_LOGIN_SUC: "AUTH_LOGIN_SUC",
    AUTH_LOGOUT_SUC: "AUTH_LOGOUT_SUC",
    AUTH_GOOGLE_SUC: "AUTH_GOOGLE_SUC",
  },
  PROJECT: {
    NOT_FOUND: "PROJECT_NOT_FOUND",
    UNAUTHORIZED: "PROJECT_UNAUTHORIZED",
  },
  GEN:{
    TECHNICAL_ERR: 'TECHNICAL_ERR',
  }
};
