import { API_CODES as SHARED_API_CODES } from "@ra/shared";
export const API_CODES = {
  AUTH: {
    THERE_IS_A_USER_ALREADY_WITH_EMAIL: "THERE_IS_A_USER_ALREADY_WITH_EMAIL",
    INVALID_USER: "INVALID_USER",
    GOOGLE_LOGIN_FAILED: "GOOGLE_LOGIN_FAILED",
    TECHNICAL_ERR: 'TECHNICAL_ERR',
    USERNAME_PASSWORD_INCORRECT: "USERNAME_PASSWORD_INCORRECT",
    TOKEN_EXPIRED : "TOKEN_EXPIRED",
    NO_REFRESH_TOKEN : "NO_REFRESH_TOKEN",
    INVALID_REFRESH_TOKEN : "INVALID_REFRESH_TOKEN",
    AUTH_HEADER_MISSING : "AUTH_HEADER_MISSING",
    INVALID_AUTH_HEADER : "INVALID_AUTH_HEADER",
    USER_NOT_FOUND : "USER_NOT_FOUND",
    AUTH_REFRESH_TOKEN_SUC: "AUTH_REFRESH_TOKEN_SUC",
    AUTH_LOGIN_SUC: "AUTH_LOGIN_SUC",
    AUTH_LOGOUT_SUC: "AUTH_LOGOUT_SUC",
    AUTH_GOOGLE_SUC: "AUTH_GOOGLE_SUC",
  },
  ANALYSIS: {
    NO_EXTRACTED_DATA:"NO_EXTRACTED_DATA",
    ERROR_WHILE_ANALYSING: "ERROR_WHILE_ANALYSING",
    ANALYSIS_SUC: "ANALYSIS_SUC",
    ANALYSIS_NOT_FOUND: "ANALYSIS_NOT_FOUND",
    ERROR_WHILE_FETCHING_ANALYSIS: "ERROR_WHILE_FETCHING_ANALYSIS",
    FEEDBACK_UPDATED_SUC: "FEEDBACK_UPDATED_SUC",
    ERROR_WHILE_UPDATING_FEEDBACK: "ERROR_WHILE_UPDATING_FEEDBACK"
  },
  JOB_ANALYZER: {
    EXTRACT_SUC: "JOB_KEYWORDS_EXTRACT_SUC",
    EXTRACT_FAILED: "JOB_KEYWORDS_EXTRACT_FAILED",
    NO_INPUT: "JOB_ANALYZER_NO_INPUT",
    MATCH_SUC: "JOB_MATCH_SUC",
    MATCH_FAILED: "JOB_MATCH_FAILED",
    MATCH_NOT_FOUND: "JOB_MATCH_NOT_FOUND",
    PENDING_ADD_SUC: "PENDING_COMPARISON_ADD_SUC",
    PENDING_LIST_SUC: "PENDING_COMPARISON_LIST_SUC",
    PENDING_REMOVE_SUC: "PENDING_COMPARISON_REMOVE_SUC",
    PENDING_NOT_FOUND: "PENDING_COMPARISON_NOT_FOUND",
  },
  ...SHARED_API_CODES
};
