export const API_CODES = {
  RESUME: {
    UNABLE_PARSE_THE_FILE : "UNABLE_PARSE_THE_FILE",
    UPLOAD_SUC : "UPLOAD_SUC",
    NO_FILE_UPLOAD : "NO_FILE_UPLOAD",
    UPLOAD_FAILED : "UPLOAD_FAILED",
    FETCH_SUC : "FETCH_SUC",
    FETCH_FAILED : "FETCH_FAILED",
    DELETE_SUC : "DELETE_SUC",
    DELETE_FAILED : "DELETE_FAILED",
  },
  GEN:{
    TECHNICAL_ERR: 'TECHNICAL_ERR',
  }
};
